positive = [
    "train",
    "amazing",
    "awesome",
    "blithesome",
    "excellent",
    "fabulous",
    "fantastic",
    "favorable",
    "fortuitous",
    "great",
    "incredible",
    "ineffable",
    "mirthful",
    "outstanding",
    "perfect",
    "propitious",
    "remarkable",
    "smart",
    "spectacular",
    "splendid",
    "stupendous",
    "super",
    "ultimate",
    "unbelievable",
    "wondrous",
]
negative = [
    "sad",
    "bad",
    "terrible",
    "horrible",
    "dismal",
    "lame",
    "abysmal",
    "appalling",
    "atrocious",
    "awful",
    "dreadful",
    "egregious",
    "horrendous",
    "horrible",
    "lousy",
    "nasty",
    "poor",
    "rotten",
    "shoddy",
    "subpar",
    "terrible",
    "unfortunate",
    "unhappy",
    "unsatisfactory",
    "unsavory",
    "vile",
    "wretched",
]
neutral = [
    "adequate",
    "average",
    "decent",
    "fair",
    "fine",
    "mediocre",
    "ordinary",
    "passable",
    "satisfactory",
    "sufficient",
    "tolerable",
]
Interests = [
    "gaming",
    "valorant",
    "music",
    "reading",
    "genshin",
    "coding",
    "genshin impact",
    "lofi",
    "anime",
    "minecraft",
    "art",
    "drawing",
    "writing",
    "pokemon",
    "realta"
    ]
hello = [
    "hello",
    "hi",
    "hey",
    "greetings",
    "salutations",
    "howdy",
    "yo",
    "hiya",
    "sup",
    "ahoy",
    "bonjour",
    "hola",
    "heyo",
    "hihi",
    "hullo",
    "01001000 01100101 01101100 01101100 01101111",
    "wassup",
    "hey there",
    "good morrow",
    "blessings",
    "meowlo",
    "peekaboo",
    "boop",
    "o hai",
    "pew pew",
    "zoinks",
    "yoohoo",
    "chirp chirp",
    "cozy hi",
    "yo yo yo",
    "what’s poppin’",
    "ayy",
    "squad up",
    "hi fam",
    "hey bestie",
    "wig snatched hi",
    "it’s giving greeting",
    "g’day",
    "top of the mornin’",
    "cheers",
    "holla",
    "salve",
    "namaste",
    "salaam",
    "konnichiwa",
    "ni hao",
    "annyeong",
    "zdravstvuyte",
    "shalom",
    "hei",
    "hej",
    "selamat pagi",
    "kumusta",
    "jambo",
    "xin chào",
    "aloha",
    "privet",
    "ciao",
    "hola hola",
    "bonjourno",
    "sannu",
    "barev",
    "mbote",
    "szia",
    "yassas",
    "merhaba",
    "tēnā koe",
    "greetings, traveler",
    "ping",
    "system online",
    "booting up… hi",
    "access granted",
    "incoming transmission",
    "AI says hi",
    "console says hello",
    "welcome, user",
    "hello, world",


]
bye = [
    "bye",
    "goodbye",
    "bye",
    "see you",
    "farewell",
    "take care",
    "later",
    "ciao",
    "adios",
    "sayonara",
    "au revoir",
    "tschüss",
    "shalom",
    "namaste",
    "peace out",
    "catch you later",
    "until next time",
    "see ya",
    "bye bye",
    "toodles",
    "cheerio",
]